name: Pylint

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  lint:
    name: PyLint Check
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: run pylint score updater file
        run: python ./utils/pylint_score_updater.py

      - name: config git user identity
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"

      - name: commit and push changes
        run: |
          git add README.md
          git commit -m "automatically update pylint score in the badge"
          git push
